import { test } from "node:test";
import assert from "node:assert/strict";

import { autoBold, bbToHtml, buildFullReport, type ReportInput } from "./bbcode.ts";

/**
 * Parity fixtures captured from the ORIGINAL implementation in public/app.js
 * before it was deleted. These expected values are literal — they were
 * generated by running the old code, not by running the new code.
 *
 * If a change makes one of these fail, the report output has drifted from what
 * deputies are already posting to the forum. Fix the change, not the fixture.
 */

interface AutoBoldCase {
  input: string;
  expected: string;
}

interface BbToHtmlCase {
  input: string;
  expected: string;
}

interface ReportCase {
  name: string;
  input: ReportInput;
  expected: string;
}

const AUTO_BOLD_CASES: AutoBoldCase[] = [
  { input: "Pada 17/09/2026 pukul 21:30, Deputy John Smith melakukan traffic stop di Vinewood Boulevard.", expected: "Pada [b]17/09/2026[/b] [b]pukul 21:30[/b], [b]Deputy John Smith[/b] melakukan [b]traffic stop[/b] di [b]Vinewood Boulevard[/b]." },
  { input: "Suspect berwarna merah dengan Plate Nomor ABC1234 melarikan diri.", expected: "[b]Suspect[/b] [b]berwarna merah[/b] dengan [b]Plate Nomor ABC1234[/b] melarikan diri." },
  { input: "Korban mengatakan karena perampokan bersenjata di area lokasi Station.", expected: "[b]Korban[/b] mengatakan [b]karena[/b] [b]perampokan bersenjata[/b] di [b]area[/b] [b]lokasi[/b] Station." },
  { input: "Sudah ada [b]bold[/b] lalu 12 Januari 2026 dan Deputy Jane Doe.", expected: "Sudah ada [b]bold[/b] lalu [b]12 Januari 2026[/b] dan [b]Deputy Jane Doe[/b]." },
  { input: "kendaraan berjenis Sultan RS berwarna hitam, model 2013.", expected: "[b]kendaraan berjenis Sultan RS[/b] [b]berwarna hitam[/b], [b]model 2013[/b]." },
  { input: "Tidak ada yang cocok di sini.", expected: "Tidak ada yang cocok di sini." },
  { input: "-", expected: "-" },
  { input: "", expected: "" },
  { input: "Witness: Officer Bob Lee tiba jam 09.05 di Mirror Park Avenue.", expected: "[b]Witness[/b]: [b]Officer Bob Lee[/b] tiba [b]jam 09.05[/b] di [b]Mirror Park Avenue[/b]." },
  { input: "Pada 1 Januari 2026, Sergeant Major Lee dan Detective Smith tiba.", expected: "Pada [b]1 Januari 2026[/b], [b]Sergeant Major Lee[/b] dan [b]Detective Smith[/b] tiba." },
  { input: "Pelaku melakukan armed robbery lalu reckless evading di Route 68.", expected: "[b]Pelaku[/b] melakukan [b]armed robbery[/b] lalu reckless evading di Route 68." },
  { input: "License Plate XYZ-99 dan Plat Nomor BD 1234 ZZ ditemukan.", expected: "[b]License Plate XYZ-99[/b] dan [b]Plat Nomor BD[/b] 1234 ZZ ditemukan." },
  { input: "vehicle model Elegy dengan warna biru, alasan karena pursuit.", expected: "[b]vehicle model Elegy[/b] dengan [b]warna biru[/b], [b]alasan[/b] [b]karena[/b] [b]pursuit[/b]." },
  { input: "multiple\nline\ninput dengan 10.30 dan 22/12/2025", expected: "multiple\nline\ninput dengan [b]10.30[/b] dan [b]22/12/2025[/b]" },
  { input: "Sudah [b]ada bold[/b] dan [b]lagi[/b] plus 05/03/2026.", expected: "Sudah [b]ada bold[/b] dan [b]lagi[/b] plus [b]05/03/2026[/b]." },
  { input: "Model, kendaraan berjenis Futo berwarna putih.", expected: "Model, [b]kendaraan berjenis Futo[/b] [b]berwarna putih[/b]." },
  { input: "saksi melihat suspect di Mirror Park Boulevard, pukul 14.00.", expected: "[b]saksi[/b] melihat [b]suspect[/b] di [b]Mirror Park Boulevard[/b], [b]pukul 14.00[/b]." },
  { input: "STATION dan Area dan LOKASI huruf besar semua.", expected: "STATION dan [b]Area[/b] dan [b]LOKASI[/b] huruf besar semua." },
  { input: "Deputy Sheriff Trainee John Doe reporting.", expected: "[b]Deputy Sheriff Trainee John Doe[/b] reporting." },
  { input: "time 23:59 dan jam 00.00 dan pukul 12:30.", expected: "[b]time 23:59[/b] dan [b]jam 00.00[/b] dan [b]pukul 12:30[/b]." },
];

const BB_TO_HTML_CASES: BbToHtmlCase[] = [
  { input: "[b]Bold[/b] dan [i]italic[/i].", expected: "<b>Bold</b> dan <i>italic</i>." },
  { input: "[divbox=white]\nNested white\n[/divbox]", expected: "<div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br>Nested white<br></div>" },
  { input: "[divbox=#008040]\n[center][b][color=#FFFFFF]Los Santos Sheriff Department[/color][/b][/center]\n[/divbox]", expected: "<div style=\"background:#008040;border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br><div style=\"text-align:center\"><b><span style=\"color:#FFFFFF\">Los Santos Sheriff Department</span></b></div><br></div>" },
  { input: "[divbox=white]\n[b]Outer[/b]\n[divbox=#008040]\n[center][b][color=#FFFFFF]Inner[/color][/b][/center]\n[/divbox]\n[divbox=white]\nNested white\n[/divbox]\n[/divbox]", expected: "<div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br><b>Outer</b><br><div style=\"background:#008040;border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br><div style=\"text-align:center\"><b><span style=\"color:#FFFFFF\">Inner</span></b></div><br></div><br><div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br>Nested white<br></div><br></div>" },
  { input: "[spoiler][img]https://x.com/a.png[/img][/spoiler]", expected: "<details><summary>Spoiler</summary><img src=\"https://x.com/a.png\" style=\"max-width:100%;border-radius:4px;margin:4px 0\"></details>" },
  { input: "[center][img]https://imagizer.imageshack.com/v2/200x200q70/924/Rs1Hi8.png[/img][/center]", expected: "<div style=\"text-align:center\"><img src=\"https://imagizer.imageshack.com/v2/200x200q70/924/Rs1Hi8.png\" style=\"max-width:100%;border-radius:4px;margin:4px 0\"></div>" },
  { input: "plain text\nwith newline", expected: "plain text<br>with newline" },
  { input: "[divbox=white]\n[b]First Report - Title[/b]\n\n[b]Date:[/b]\n[divbox=white] 17/09/2026 [/divbox]\n\n[b]Details:[/b]\n[divbox=white] [b]Deputy John Smith[/b] [/divbox]\n\n[b]Evidence:[/b]\n[divbox=white] \n[spoiler][img]https://a.com/1.png[/img][/spoiler]\n[/divbox]\n\n[/divbox]", expected: "<div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br><b>First Report - Title</b><br><br><b>Date:</b><br><div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"> 17/09/2026 </div><br><br><b>Details:</b><br><div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"> <b>Deputy John Smith</b> </div><br><br><b>Evidence:</b><br><div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"> <br><details><summary>Spoiler</summary><img src=\"https://a.com/1.png\" style=\"max-width:100%;border-radius:4px;margin:4px 0\"></details><br></div><br><br></div>" },
  { input: "[color=red]red[/color] and [color=#00ff00]green[/color]", expected: "<span style=\"color:red\">red</span> and <span style=\"color:#00ff00\">green</span>" },
  { input: "", expected: "" },
];

const REPORT_CASES: ReportCase[] = [
  {
    name: "full report with evidence",
    input: {"name":"John Smith","station":"Paleto Bay","rank":"Deputy Sheriff","badge":"1234","first":{"title":"Traffic Stop","date":"2026-09-17","details":"Pada 17/09/2026 pukul 21:30, Deputy John Smith melakukan traffic stop di Vinewood Boulevard.","evidence":["https://a.com/1.png"]},"second":{"title":"Armed Robbery","date":"2026-09-18","details":"Suspect berwarna merah dengan Plate Nomor ABC1234.","evidence":["https://a.com/2.png","https://a.com/3.png"]}},
    expected: "[divbox=white]\n[center][img]https://imagizer.imageshack.com/v2/200x200q70/924/Rs1Hi8.png[/img][/center]\n[/divbox]\n[divbox=#008040]\n[center][b][color=#FFFFFF]Los Santos Sheriff Department[/color][/b][/center]\n[/divbox]\n\n[divbox=white]\n[center][b]Patrol Report[/b][/center]\n[divbox=white]\n[b]Name:[/b] John Smith\n[b]Station:[/b] Paleto Bay\n[b]Rank:[/b] Deputy Sheriff\n[b]Badge:[/b] 1234\n[/divbox]\n\n[divbox=white]\n[b]First Report - Traffic Stop[/b]\n\n[b]Date:[/b]\n[divbox=white] 17/09/2026 [/divbox]\n\n[b]Details:[/b]\n[divbox=white] Pada [b]17/09/2026[/b] [b]pukul 21:30[/b], [b]Deputy John Smith[/b] melakukan [b]traffic stop[/b] di [b]Vinewood Boulevard[/b]. [/divbox]\n\n[b]Evidence:[/b]\n[divbox=white] \n[spoiler][img]https://a.com/1.png[/img][/spoiler]\n[/divbox]\n\n[/divbox]\n\n[divbox=white]\n[b]Second Report - Armed Robbery[/b]\n\n[b]Date:[/b]\n[divbox=white] 18/09/2026 [/divbox]\n\n[b]Details:[/b]\n[divbox=white] [b]Suspect[/b] [b]berwarna merah[/b] dengan [b]Plate Nomor ABC1234[/b]. [/divbox]\n\n[b]Evidence:[/b]\n[divbox=white] \n[spoiler][img]https://a.com/2.png[/img][/spoiler]\n[spoiler][img]https://a.com/3.png[/img][/spoiler]\n[/divbox]\n\n[/divbox]\n[/divbox]",
  },
  {
    name: "empty report (all fallbacks)",
    input: {"name":"","station":"","rank":"","badge":"","first":{"title":"","date":"","details":"","evidence":[]},"second":{"title":"","date":"","details":"","evidence":[]}},
    expected: "[divbox=white]\n[center][img]https://imagizer.imageshack.com/v2/200x200q70/924/Rs1Hi8.png[/img][/center]\n[/divbox]\n[divbox=#008040]\n[center][b][color=#FFFFFF]Los Santos Sheriff Department[/color][/b][/center]\n[/divbox]\n\n[divbox=white]\n[center][b]Patrol Report[/b][/center]\n[divbox=white]\n[b]Name:[/b] Answer\n[b]Station:[/b] Answer\n[b]Rank:[/b] Answer\n[b]Badge:[/b] Answer\n[/divbox]\n\n[divbox=white]\n[b]First Report - <Insert Report Title>[/b]\n\n[b]Date:[/b]\n[divbox=white] - [/divbox]\n\n[b]Details:[/b]\n[divbox=white] - [/divbox]\n\n[b]Evidence:[/b]\n[divbox=white] \n-\n[/divbox]\n\n[/divbox]\n\n[divbox=white]\n[b]Second Report - <Insert Report Title>[/b]\n\n[b]Date:[/b]\n[divbox=white] - [/divbox]\n\n[b]Details:[/b]\n[divbox=white] - [/divbox]\n\n[b]Evidence:[/b]\n[divbox=white] \n-\n[/divbox]\n\n[/divbox]\n[/divbox]",
  },
  {
    name: "no evidence, has details",
    input: {"name":"Jane Doe","station":"Roxwood","rank":"Sergeant","badge":"99","first":{"title":"Patrol","date":"2026-01-01","details":"Patroli rutin.","evidence":[]},"second":{"title":"Backup","date":"2026-01-02","details":"Korban mengatakan karena perampokan bersenjata di area lokasi Station.","evidence":[]}},
    expected: "[divbox=white]\n[center][img]https://imagizer.imageshack.com/v2/200x200q70/924/Rs1Hi8.png[/img][/center]\n[/divbox]\n[divbox=#008040]\n[center][b][color=#FFFFFF]Los Santos Sheriff Department[/color][/b][/center]\n[/divbox]\n\n[divbox=white]\n[center][b]Patrol Report[/b][/center]\n[divbox=white]\n[b]Name:[/b] Jane Doe\n[b]Station:[/b] Roxwood\n[b]Rank:[/b] Sergeant\n[b]Badge:[/b] 99\n[/divbox]\n\n[divbox=white]\n[b]First Report - Patrol[/b]\n\n[b]Date:[/b]\n[divbox=white] 01/01/2026 [/divbox]\n\n[b]Details:[/b]\n[divbox=white] [b]Patroli[/b] rutin. [/divbox]\n\n[b]Evidence:[/b]\n[divbox=white] \n-\n[/divbox]\n\n[/divbox]\n\n[divbox=white]\n[b]Second Report - Backup[/b]\n\n[b]Date:[/b]\n[divbox=white] 02/01/2026 [/divbox]\n\n[b]Details:[/b]\n[divbox=white] [b]Korban[/b] mengatakan [b]karena[/b] [b]perampokan bersenjata[/b] di [b]area[/b] [b]lokasi[/b] Station. [/divbox]\n\n[b]Evidence:[/b]\n[divbox=white] \n-\n[/divbox]\n\n[/divbox]\n[/divbox]",
  },
];

test("autoBold matches the original implementation", () => {
  for (const { input, expected } of AUTO_BOLD_CASES) {
    assert.equal(autoBold(input), expected, `autoBold drifted for: ${JSON.stringify(input)}`);
  }
});

test("bbToHtml matches the original implementation", () => {
  for (const { input, expected } of BB_TO_HTML_CASES) {
    assert.equal(bbToHtml(input), expected, `bbToHtml drifted for: ${JSON.stringify(input)}`);
  }
});

test("buildFullReport matches the original implementation", () => {
  for (const { name, input, expected } of REPORT_CASES) {
    assert.equal(buildFullReport(input), expected, `buildFullReport drifted for case: ${name}`);
  }
});

test("the report header keeps its literal image URL", () => {
  const report = buildFullReport(REPORT_CASES[0].input);
  assert.ok(
    report.includes("https://imagizer.imageshack.com/v2/200x200q70/924/Rs1Hi8.png"),
    "the ImageShack header image URL must survive byte-for-byte",
  );
});


/* ============================================================================
   Adversarial fixtures — the machinery in autoBold is subtle enough that a
   well-meaning cleanup can change the bytes without any obvious signal.

   Two hazards are pinned here:

   1. The final reduce uses STRING replacement (`.replace(placeholder, val)`),
      so a `$` in the captured text is treated as a substitution pattern.
      "[b]win $& lose[/b]" really does emit "[b]win @@B0@@ lose[/b]" — the
      placeholder leaks into the output. That is the shipped behaviour and must
      be preserved; the "correct" `.replaceAll(p, () => val)` fix would change
      what deputies post.

   2. A literal "@@B0@@" in the input collides with the placeholder namespace
      and moves text around.

   Both look like bugs. They ARE bugs. They are also the current contract, so
   they are pinned rather than fixed.
   ========================================================================= */

const AUTO_BOLD_ADVERSARIAL: AutoBoldCase[] = [
  { input: "[b]win $& lose[/b]", expected: "[b]win @@B0@@ lose[/b]" },
  { input: "[b]a $` b[/b]", expected: "[b]a  b[/b]" },
  { input: "[b]a $' b[/b]", expected: "[b]a  b[/b]" },
  { input: "[b]cost $100[/b]", expected: "[b]cost $100[/b]" },
  { input: "karena @@B0@@ pukul 10:00", expected: "[b]karena[/b] [b]pukul 10:00[/b] @@B0@@" },
  { input: "[b]x[/b] $$ and $1", expected: "[b]x[/b] $$ and $1" },
  { input: "[b]one[/b] [b]two[/b] [b]three[/b] 17/09/2026", expected: "[b]one[/b] [b]two[/b] [b]three[/b] [b]17/09/2026[/b]" },
  { input: "Deputy A lalu Deputy B lalu Deputy C", expected: "[b]Deputy A[/b] lalu [b]Deputy B[/b] lalu [b]Deputy C[/b]" },
  { input: "[b]@@B0@@[/b]", expected: "[b]@@B0@@[/b]" },
  { input: "@@B0@@ @@B1@@", expected: "@@B0@@ @@B1@@" },
  { input: "pad 17/09/2026 jam 21:30 di Vinewood Boulevard", expected: "pad [b]17/09/2026[/b] [b]jam 21:30[/b] di [b]Vinewood Boulevard[/b]" },
];

const BB_TO_HTML_ADVERSARIAL: BbToHtmlCase[] = [
  { input: "[divbox=white]\n[divbox=white]\n[divbox=white]\ndeep\n[/divbox]\n[/divbox]\n[/divbox]", expected: "<div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br><div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br><div style=\"background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br>deep<br></div><br></div><br></div>" },
  { input: "[divbox=#008040]\n[b]x[/b]\n[/divbox]", expected: "<div style=\"background:#008040;border:1px solid var(--border);border-radius:6px;padding:10px;margin:6px 0\"><br><b>x</b><br></div>" },
  { input: "a\n\n\nb", expected: "a<br><br><br>b" },
  { input: "[b]unclosed", expected: "[b]unclosed" },
  { input: "[/b]stray[/b]", expected: "[/b]stray[/b]" },
];

test("autoBold preserves the placeholder and $ substitution quirks", () => {
  for (const { input, expected } of AUTO_BOLD_ADVERSARIAL) {
    assert.equal(autoBold(input), expected, `autoBold drifted for: ${JSON.stringify(input)}`);
  }
});

test("bbToHtml handles nesting, malformed tags and blank lines", () => {
  for (const { input, expected } of BB_TO_HTML_ADVERSARIAL) {
    assert.equal(bbToHtml(input), expected, `bbToHtml drifted for: ${JSON.stringify(input)}`);
  }
});

test("autoBold is idempotent for already-bold text", () => {
  // The placeholder pass exists so existing [b] spans are not re-wrapped.
  const once = autoBold("[b]Deputy John Smith[/b] at 17/09/2026");
  assert.equal(once, "[b]Deputy John Smith[/b] at [b]17/09/2026[/b]");
});
